---
before_install:
  - wget http://www.rabbitmq.com/releases/rabbitmq-server/v3.0.4/rabbitmq-server_3.0.4-1_all.deb
  - sudo dpkg -i rabbitmq-server_3.0.4-1_all.deb
  - sudo /etc/init.d/rabbitmq-server stop
  - sudo rabbitmq-plugins list
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo /etc/init.d/rabbitmq-server start
  - sudo apt-get install aspell
  - cpanm Module::Install
  - cpanm Module::Install::AuthorRequires
  - cpanm Module::Install::AuthorTests
  - cpanm Module::Install::Authority
  - cpanm Test::Pod
  - cpanm Test::NoTabs
  - cpanm Test::Pod::Coverage
  - cpanm Pod::Coverage
  - cpanm Pod::Coverage::TrustPod
  - cpanm Test::Spelling
  - cpanm JSON
  - cpanm Net::Stomp
language: perl
notifications:
  irc: irc.perl.org#message-passing
perl:
  - 5.16
  - 5.14
  - 5.12
  - 5.10
